# 1. Créer un workflow `02_test.yml` qui :
#    - Se déclenche sur push et pull request
#    - Configure Python 3.11.9
#    - Installe les dépendances
#    - Exécute les tests avec pytest
name: Test API Satisfaction
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9
      - name: Installation des dépendances
        run: npm ci
      - name: Run tests with pytest
        run: |
          pytest api_prediction/test_app_satisfaction.py
